version: "3"
services:
  portainer:
    image: portainer/portainer:latest
    command: --no-auth -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  traefik:
    image: library/traefik:latest
    command: --docker --docker.swarmmode --docker.domain=traefik --docker.watch --web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  instance:
    image: library/plone:latest
    hostname: plone
    networks:
      - traefik-net
      - zeo-net
    environment:
      - ZEO_ADDRESS=zeo:8100
    deploy:
      replicas: 2
      labels:
        traefik.docker.network: traefik-net
        traefik.port: 8080
        traefik.frontend.rule: Host:plone.traefik #;AddPrefix:/VirtualHostBase/http/plone.traefik:80/Plone/VirtualHostRoot
        traefik.backend.loadbalancer.method: drr

  zeo:
    hostname: zeo
    image: library/plone:latest
    command: zeoserver
    volumes:
      - zeo-data:/data
    networks:
      - zeo-net
    deploy:
      mode: global
  
  varnish:
    image: eeacms/varnish
    environment:
      - BACKENDS=traefik
      - DNS_ENABLED=true
    networks:
      - traefik-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.docker.network: traefik-net
        traefik.port: 6081

volumes:
    zeo-data:

networks:
  traefik-net:
    driver: overlay    
  zeo-net:
    driver: overlay
