version: "3"
services:
  portainer:
    image: portainer/portainer:latest
    command: --no-auth
    ports:
      - "9000:9000"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  traefik:
    image: library/traefik:latest
    command: --docker --docker.swarmmode --docker.domain=traefik --docker.watch --web
    ports:
      - "8080:8080"
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  varnish:
    build: varnish
    image: varnish
    ports:
      - "80:80"
    environment:
      - BACKENDS=traefik
      - BACKENDS_PORT=80
      - DNS_ENABLED=true
    networks:
      - traefik-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

volumes:
    zeo-data:

networks:
    traefik-net:
      external:
        name: traefik-net
